export default [
  { value: 'banuser', label: 'ban user' },
  { value: 'unbanuser', label: 'unban user' },
  { value: 'removelink', label: 'remove link' },
  { value: 'approvelink', label: 'approve link' },
  { value: 'removecomment', label: 'remove comment' },
  { value: 'approvecomment', label: 'approve comment' },
  { value: 'addmoderator', label: 'add moderator' },
  { value: 'invitemoderator', label: 'invite moderator' },
  { value: 'uninvitemoderator', label: 'uninvite moderator' },
  { value: 'acceptmoderatorinvite', label: 'accept moderator invite' },
  { value: 'removemoderator', label: 'remove moderator' },
  { value: 'addcontributor', label: 'add contributor' },
  { value: 'removecontributor', label: 'remove contributor' },
  { value: 'editsettings', label: 'edit settings' },
  { value: 'editflair', label: 'edit flair' },
  { value: 'distinguish', label: 'distinguish' },
  { value: 'marknsfw', label: 'mark nsfw' },
  { value: 'wikibanned', label: 'wiki ban' },
  { value: 'wikiunbanned', label: 'wiki unban' },
  { value: 'wikicontributor', label: 'add wiki contributor' },
  { value: 'removewikicontributor', label: 'remove wiki contributor' },
  { value: 'wikipagelisted', label: 'wiki page listed' },
  { value: 'wikirevise', label: 'revise wiki' },
  { value: 'wikipermlevel', label: 'change wiki perm level' },
  { value: 'ignorereports', label: 'ignore reports' },
  { value: 'unignorereports', label: 'unignore reports' },
  { value: 'setpermissions', label: 'set permissions' },
  { value: 'setsuggestedsort', label: 'set suggested sort' },
  { value: 'sticky', label: 'sticky' },
  { value: 'unsticky', label: 'unsticky' },
  { value: 'setcontestmode', label: 'set contest mode' },
  { value: 'unsetcontestmode', label: 'unset contest mode' },
  { value: 'lock', label: 'lock' },
  { value: 'unlock', label: 'unlock' },
  { value: 'muteuser', label: 'mute user' },
  { value: 'unmuteuser', label: 'unmute user' },
  { value: 'createrule', label: 'create rule' },
  { value: 'editrule', label: 'edit rule' },
  { value: 'deleterule', label: 'delete rule' },
  { value: 'spoiler', label: 'mark as spoiler' },
  { value: 'unspoiler', label: 'unmark as spoiler' },
];
