#!/bin/bash -e

DUMP_DIRECTORY=mongodump-$(date +%Y-%m-%d)
GZIP_ARCHIVE=$DUMP_DIRECTORY.tgz

cd /tmp
mongodump -o $DUMP_DIRECTORY -h mongo --numParallelCollections=1
tar czf $GZIP_ARCHIVE $DUMP_DIRECTORY

aws \
  --region $GLACIER_BACKUP_REGION \
  glacier upload-archive \
  --account-id - \
  --vault-name $GLACIER_BACKUP_VAULT \
  --body $GZIP_ARCHIVE

rm -rf $DUMP_DIRECTORY
rm $GZIP_ARCHIVE
