#!/bin/sh

docker build -t "$DOCKER_REPO":web -f docker/web/Dockerfile --build-arg ANALYTICS_KEY="$ANALYTICS_KEY" .
docker build -t "$DOCKER_REPO":worker -f docker/worker/Dockerfile .
docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
docker push "$DOCKER_REPO"

ssh -i scripts/deploy_key -o "StrictHostKeyChecking no" "$DEPLOY_USER"@"$DEPLOY_HOST" <<ENDDEPLOY
cd /srv/modlogs/app
sudo git pull origin master
cd docker
sudo docker login -u='$DOCKER_USERNAME' -p='$DOCKER_PASSWORD'
sudo docker-compose pull --parallel

NODE_ENV=production \
LOG_LEVEL=info \
APP_ID='$APP_ID' \
APP_SECRET='$APP_SECRET' \
REDDIT_USER='$REDDIT_USER' \
REDDIT_PASSWORD='$REDDIT_PASSWORD' \
USER_AGENT='$USER_AGENT' \
sudo -E docker-compose up -d

ENDDEPLOY
